name: auto regenerate homepage

on: push

jobs:
  regenerate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Other steps that change files in the repository
      - name: Execute Python script
        run: |
          python homepage.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5

