name: Auto regenerate homepage
on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - ".github/workflows/auto-hompage.yml"

jobs:
  # Auto regenerate homepage
  regenerate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5

      # Other steps that change files in the repository
      - name: Execute Python script
        run: |
          python homepage.py

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --cached --quiet; then  
            echo "No changes to commit"  
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else  
            git commit -m "feat: auto reg homepage" -a
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      # - name: Push changes
      #   if: ${{ steps.commit.outputs.has_changes == 'true' }}
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.DEPLOY_GH }}
      #     branch: ${{ github.head_ref }}
      - name: Create Pull Request
        if: ${{ steps.commit.outputs.has_changes == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.DEPLOY_GH }}
          title: "feat: auto reg homepage"
          commit-message: "feat: auto reg homepage"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: create-pull-request/patch-auto-reg-homepage
          base: master
          labels: |
            report
            automated pr
          assignees: DrAugus
          # Review cannot be requested from pull request author.
          # reviewers: DrAugus